#partial config/filelist created for Fire Emblem: Three Houses V1.2.0

fe3h:
  'DATA1.bin': './DATA1.bin'
  'BGM.ktsl2stbin': './nx/sound/BGM.ktsl2stbin'
  'gwscrdata.bin': './patch1/common/common/gwscrdata.bin'
  'fixed_calendardata.bin': './patch3/nx/data/fixed_calendardata.bin'
  'btlscrdata.bin': './patch4/common/common/btlscrdata.bin'
  'msgdata.bin': './patch4/common/common/msgdata.bin'
  'scrdata.bin': './patch4/common/common/scrdata.bin'
  'tuscrdata.bin': './patch4/common/common/tuscrdata.bin'
  'fixed_act_data.bin': './patch4/nx/data/fixed_act_data.bin'
  'fixed_classdata.bin': './patch4/nx/data/fixed_classdata.bin'
  'fixed_data.bin': './patch4/nx/data/fixed_data.bin'
  'fixed_groupworkdata.bin': './patch4/nx/data/fixed_groupworkdata.bin'
  'fixed_lobby_activity.bin': './patch4/nx/data/fixed_lobby_activity.bin'
  'fixed_growthdata.bin': './patch4/nx/data/fixed_growthdata.bin'
  'fixed_lobby_common.bin': './patch4/nx/data/fixed_lobby_common.bin'
  'fixed_lobby_quest.bin': './patch4/nx/data/fixed_lobby_quest.bin'
  'fixed_persondata.bin': './patch4/nx/data/fixed_persondata.bin'
  'fixed_presentdata.bin': './patch4/nx/data/fixed_presentdata.bin'
  'fixed_scenario.bin': './patch4/nx/data/fixed_scenario.bin'
  'fixed_shopdata.bin': './patch4/nx/data/fixed_shopdata.bin'
  'INFO0.bin': './patch4/INFO0.bin'
  'INFO1.bin': './patch4/INFO1.bin'
  'INFO2.bin': './patch4/INFO2.bin'
fee_mitm:
  'person.xml.bundle': './Data/StreamingAssets/aa/Switch/fe_assets_gamedata/person.xml.bundle'
  'assettable.xml.bundle': './Data/StreamingAssets/aa/Switch/fe_assets_gamedata/assettable.xml.bundle'
  'calculator.xml.bundle': './Data/StreamingAssets/aa/Switch/fe_assets_gamedata/calculator.xml.bundle'
  'job.xml.bundle': './Data/StreamingAssets/aa/Switch/fe_assets_gamedata/job.xml.bundle'
  'params.xml.bundle': './Data/StreamingAssets/aa/Switch/fe_assets_gamedata/params.xml.bundle'
  'god.xml.bundle': './Data/StreamingAssets/aa/Switch/fe_assets_gamedata/god.xml.bundle'
fee_cobalt:
  'person.xml':'./patches/xml/person.xml'